library(rvest)
library(dplyr)
library(janitor)
library(ggplot2)
library(stringr)
library(lubridate)
library(tidyr)
library(ggrepel)
library(readr)
library(openxlsx)
library(elo)
library(ggplot2)


source('functions.R')
download_files()
source('01a_load_web_data.R')
source('01b_cleanup.R')
source('03_output.R')
